// Code generated by logcopter-gen; DO NOT EDIT.

package discodialogue

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.web-agent-example.pkg.discodialogue")
